Ensono/stacks-nx-plugins

- package-lock.json
- package.json
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
- packages/create/bin/types.ts
Add support for Next Preset.
If using the next preset, `npx @ensono-stacks/create-stacks-workspace --preset=next`, will automatically install `@ensono-stacks/next` and run the `@ensono-stacks/next:init` generator against the created project.
> feat(create): add next support for create

- packages/azure-node/src/generators/app-insights/schema.json
Just noticed these `-dir` short options while doing docs.
> fix(azure-node): short options from -dir to -e and -s

- packages/azure-node/src/generators/app-insights/generator.ts
[5416](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5416)
- returns updateDependencies -> addDependenciesToPackageJson so the callback gets invoked which installs the missing packages
> fix(azure-node): auto install app insights after generator run

- e2e/logger-e2e/tests/logger.spec.ts
- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
We often don't have stacks configured in nx.json when starting from npx @ensono-stacks/create-stacks-workspace@latest which causes workspace creation to fail. This should not happen when starting from stacks-cli, but for dev and QA purposes, it should be handy to not crash.
It will issue a warning in the console:
Supersedes #52 .
> fix(create): skip taskctl pipeline runner if stacks config is missing

- packages/next/src/generators/init/generator.ts
[5325](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5325)
The configuration is not happy when the src and destination of a build bundle is being generated. If no outputPath is supplied, the bundle is automatically created inside the dist folder which is fine. Hence the fix is just a bit of cleanup whereby removing the config if the supplied path is the same as project source.
> fix(next): removes outputPath from project json dev target build if the same as sourceRoot

- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
It looks like env vars are slightly trickier on Windows:
```
Installing Stacks dependencies
Successfully installed: @ensono-stacks/workspace @ensono-stacks/next
Configuring Stacks
Error: Command failed: HUSKY=0 git commit -m "stacks init"
'HUSKY' is not recognized as an internal or external command,
operable program or batch file.
at ChildProcess.exithandler (node:child_process:419:12)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1091:16)
at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
code: 1,
killed: false,
signal: null,
cmd: 'HUSKY=0 git commit -m "stacks init"'
}
'HUSKY' is not recognized as an internal or external command,
operable program or batch file.
```
The fix is to set `process.env['HUSKY']` as the `execAsync` …
> fix(create): fix handling env vars on Windows when executing commands

- e2e/create-e2e/tests/create.spec.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/types.ts
The `stacks-cli` integration with the create script is almost done. However there are a few blockers.
Stacks-CLI goes through the following flow when bootstrapping a project:
1. Creates the project Working Directory.
2. Runs `init` & `setup` commands from the Temp Directory.
We can't afford to install in a temp directory, as copying across `node_modules` will take way too long.
The changes to `create` introduce two new flags:
- `--dir`: the ability to set the directory into which the workspace gets created.
-  `--overwrite`: if the resolved installation path already exists, it will remove the path.
```sh
npx @ensono-stacks/create project --dir=./folder --overwrite
```
> feat(create): add support for custom dir and overwrite

- e2e/create-e2e/tests/create.spec.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/exec.ts
- packages/create/bin/types.ts
Stacks-cli controls the creation of the root project directory, and merges the working dir defined in you `stacks.yml` file with the project name.
This becomes problematic resulting in double nested folders: 
```yaml
directory:
working: /root
project:
- name: ProjectName
```
Expected: `/root/project-name`
Actual: `/root/ProjectName/project-name`
I've altered the behaviour of the flag `overwrite` to handle detecting if the `dir`'s basename matches the project name.
> fix(create): check dir name matches project name with overwrite

- e2e/create-e2e/tests/create.spec.ts
- packages/create/bin/create-stacks-workspace.ts
To fix: https://amido-dev.visualstudio.com/Amido-Stacks/_workitems/edit/5467
Issue: As part of [this PR](https://github.com/amido/stacks-nx-plugins/pull/51/files), default values were added for all the create-nx-workspace options that didn't have one already. This was to work around an issue that prevented running `create-stacks-workspaces` when those values weren't present. That issue has now been fixed, so the default values should no longer be necessary.
As a side effect of those default values, the `appName` was not gathered as an interactive option. This change reverts the default values and brings back the interactive `appName` option.
> fix(create): remove create-stacks-workspace defaults previously added

- packages/next/src/generators/init/generator.ts
- packages/next/src/generators/init/utils/eslint-fix.ts
- packages/workspace/src/generators/init/utils/eslint.ts
It looks like the code generated by `@nrwl/next` is not compatible with our eslint config :P We have to manually fix it, unfortunately :(
```
> nx run next-app-2:lint --fix
Linting "next-app-2"...
C:\Users\dphillips\Documents\code\stacks-testing-folder\0-3-3-next-workspace\apps\next-app-2\jest.config.ts
1:0  error  Specify the rules you want to disable  unicorn/no-abusive-eslint-disable
C:\Users\dphillips\Documents\code\stacks-testing-folder\0-3-3-next-workspace\apps\next-app-2\specs\index.spec.tsx
4:8  warning  Using exported name 'Index' as identifier for default export  import/no-named-as-default
✖ 2 problems (1 error, 1 warning)
```
> fix(next): eslint errors from @nrwl/next

- packages/next/src/generators/infrastructure/files/azure/build/terraform/variables.tf
- packages/next/src/generators/infrastructure/files/common/build/helm/templates/service.yaml
- packages/next/src/generators/infrastructure/utils/terraform.ts
Fixes issues 1 and 3 from https://amido-dev.visualstudio.com/Amido-Stacks/_workitems/edit/5452
1: Fix formatting of `service.yaml` file to prevent error on lint. 
3: Remove `-check` flag from `terraform-fmt` command, so that any formatting problems are automatically fixed instead of exiting out. Also fix formatting of `variables.tf` file.
> fix(next): infra files formatting errors

- packages/azure-react/src/generators/app-insights-web/generator.spec.ts
- packages/azure-react/src/generators/app-insights-web/generator.ts
- packages/azure-react/src/generators/app-insights-web/schema.json
[5471](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5471)
- throws error if connectionString is empty
- reuse --dir for directory alias
> fix(azure-react): adds check to throw error if connectionString is empty

- packages/common/core/src/utils/ignoreEntry.ts
- packages/next/src/generators/infrastructure/utils/add-infrastructure.ts
- packages/next/src/generators/infrastructure/utils/common.ts
- packages/next/src/generators/infrastructure/utils/terraform.ts
- packages/next/src/generators/init/generator.spec.ts
- packages/next/src/generators/init/generator.ts
project.json is updated in several different areas throughout the init generator.
It's updated in:
generator.ts -> updateProjectConfiguration()
generator.ts -> addCustomTestConfig()
generator.ts -> addInfrastructure() -> addCommon()
generator.ts -> addInfrastructure() -> addTerraform()
after updating the project.json, the new updated configurations must be fetched and used to merge amended project configurations within each function that alters the project configuration
> fix(next-init-infrastructure): add infrastructure related targets to project targets in init generator

- packages/azure-react/src/generators/app-insights-web/generator.ts
- packages/azure-react/src/generators/app-insights-web/utils/tsconfig.ts
- packages/azure-react/utils/versions.ts
[5471](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5471)
- bump app insights web patch version to resolve linting - https://github.com/microsoft/applicationinsights-react-js/issues/32
- update ts config to resolve linting
> fix(azure-react): updates app insights web version and ts config

- packages/create/bin/dependencies.ts
- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/generator.ts
- removes passing `e2e` in the create script as this is added inside the playwright init generator and the passed value needs to be an existing project
- updates unit test
- adds @mands/nx-playwright to devDep for new project (executor e2e purposes)
> fix(playwright): update project name passed in create script

- packages/rest-client/src/generators/bump-version/schema.json
- packages/rest-client/src/generators/client-endpoint/files/src/index.test.ts__template__
- packages/rest-client/src/generators/client-endpoint/files/src/index.ts__template__
- packages/rest-client/src/generators/client-endpoint/files/src/index.types.ts__template__
- packages/rest-client/src/generators/client-endpoint/generator.ts
- change unnecessarily complicated naming from type interfaces.
- fix the required values in the bump version generator schema
> fix(rest-client): remove version from type interfaces

- e2e/rest-client-e2e/tests/rest-client.spec.ts
- packages/common/core/src/lib/normalize-options.ts
- packages/rest-client/src/generators/bump-version/generator.spec.ts
- packages/rest-client/src/generators/bump-version/generator.ts
- packages/rest-client/src/generators/bump-version/schema.d.ts
- packages/rest-client/src/generators/bump-version/schema.json
- packages/rest-client/src/generators/client-endpoint/files/src/index.ts__template__
[5524](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5524)
- replaces both slashes when normalizing options
- import linting fix
- typeError for unacceptable project to bump version
- removes directory option for bump-version generator as it reads project list
> fix(rest-client): linting and generator config

- packages/next/src/generators/next-auth-redis-deployment/files/azure/deploy/terraform/variables/nonprod/redis.tfvars
- packages/next/src/generators/next-auth-redis-deployment/files/azure/deploy/terraform/variables/prod/redis.tfvars
- packages/next/src/generators/next-auth-redis-deployment/generator.ts
Ticket [5761](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5761)
- Change redis_name in terraform to use application name by default
> feat(next): use application name as redis name instead of resource group

- packages/azure-node/src/generators/app-insights-deployment/generator.ts
- packages/azure-node/src/generators/app-insights-deployment/utils/update-pipeline.ts
If the app insights connection string is set in an ADO variable group as a secret then it will not set correctly during the deployment. The workaround is to set it as an environment variable on the deployment step.
- Find correct deployment step
- Update environment variables in stages yaml
> fix(azure-node): update pipeline stages yaml for app insights

- packages/next/src/generators/init-deployment/files/apps/common/Dockerfile
Ticket: [5792](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5792)
- Remove with-nx.json copy from the dockerfile
- Requires the latest version of nx and nrwl/next to work
> fix(next): remove with-nx copy from dockerfile

- packages/next/src/generators/init-deployment/utils/common.ts
Updated init-deployment to allowEmptyRelease when running the semver:version executor. 
In cases where Nx wants to rebuild/deploy applications (i.e due to a workspace change such as dependency updates) semver will not version the application if it would be an empty release. However, we need to enable this so that applications can deploy to a new version when workspace changes affect it
> fix(next): update init-deployment with allowEmptyRelease

- packages/next/src/generators/init-deployment/files/apps/common/deploy/helm/nonprod/values.yaml
- packages/next/src/generators/init-deployment/files/apps/common/deploy/helm/prod/values.yaml
- packages/next/src/generators/init-deployment/files/libs/common/build/helm/values.yaml
- packages/next/src/generators/init-deployment/generator.spec.ts
- packages/next/src/generators/init-deployment/utils/add-infrastructure.ts
- packages/next/src/generators/init-deployment/utils/common.ts
What?
Remove auto instrumentation from workspace level values.yaml and add this into the individual values.yaml files for prod/nonprod within the application deploy folders.
Why?
To enable us to set auto instrumentation for openTelemetry on a per application basis
> fix(next): Fixes for open telemetry

- packages/rest-client/src/generators/bump-version/generator.ts
Change bumpVersion function in rest client to check for path relativity
Because paths are treated differently between operating systems, therefore checking path relativity using the startsWith method will not guarantee results across OS
New isRelative function, using the path.relative function to determine if a path is a child directory of a parent
PASS   rest-client  packages/rest-client/src/generators/bump-version/generator.spec.ts
bump-version generator
√ should throw a TypeError if version is not a number (34 ms)
√ should throw an error if the endpoint doesn't exist (3 ms)
√ should throw an error if the new version is not higher (4 ms)
√ should generate the new version of the endpoint (345 ms)
√ should determine new version based on existing versions if --endpointVersion is omitted …
> fix(rest-client) Use path relation rather than startsWith

- packages/azure-node/src/generators/app-insights-deployment/generator.spec.ts
- packages/azure-node/src/generators/app-insights-deployment/generator.ts
- packages/common/core/src/utils/executedDependantGenerator.spec.ts
- packages/common/core/src/utils/executedDependantGenerator.ts
- packages/common/core/src/utils/index.ts
- packages/common/test/src/lib/stacks-attributes.ts
- packages/next/src/generators/init-deployment/generator.spec.ts
- packages/next/src/generators/init-deployment/generator.ts
- packages/playwright/src/generators/init-deployment/generator.spec.ts
- packages/playwright/src/generators/init-deployment/generator.ts
- packages/workspace/src/generators/init/generator.spec.ts
Created new util in common core to check for existing workspace generator name
For deployment generators, workspace init is a prerequisite. This enables control.
Each deployment generator calls this new util method first before continuing.
Notes for QA
> fix(common-core): Deployment generators run without relevant files in place

- packages/common/core/src/lib/normalize-options.spec.ts
- packages/next/src/generators/init/generator.spec.ts
- packages/next/src/generators/init/utils/tsconfig.ts
- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/generator.ts
Changes to multiple plugins / unit tests to cater for variance between OS behaviour.
Numerous unit tests were failing when executed on windows
Using path.join where applicable to resolve path related issues
Using tree.exists function where applicable to determine file presence
nx run-many -t test --skip-nx-cache
√  nx run common-core:test (20s)
√  nx run common-test:test (23s)
√  nx run workspace:test (26s)
√  nx run create:test (7s)
√  nx run azure-react:test (13s)
√  nx run rest-client:test (16s)
√  nx run next:test (22s)
√  nx run playwright:test (14s)
√  nx run azure-node:test (19s)
√  nx run logger:test (14s)
>  NX   Successfully ran target test for 10 projects (59s)
nx run-many -t test --skip-nx-cache
> fix(multiple) Fix/5962 windows compatibility

- packages/next/src/generators/init-deployment/generator.spec.ts
- packages/next/src/generators/init-deployment/generator.ts
- packages/next/src/generators/init-deployment/schema.d.ts
- packages/next/src/generators/init-deployment/schema.json
- packages/next/src/generators/init-deployment/utils/add-infrastructure.ts
- packages/next/src/generators/init-deployment/utils/common.ts
- packages/workspace/src/generators/init/files/lintstaged/lint-staged.config.js
Enable option to rename helm chart library when running next init deployment generator
The current naming is specific to next use case. Might be used outside of this context in future.
Add x prompt option in generator schema `libraryName` and pass value to relevant places.
Notes for QA
> feat(next): rename helm chart lib

- packages/azure-node/package.json
- packages/azure-react/package.json
- packages/logger/package.json
- packages/next/package.json
- packages/playwright/package.json
- packages/rest-client/package.json
- packages/workspace/package.json
Expect certain v15 of nx dependancy in each plugin.
To prevent higher versions being accepted for usage with our plugins (otherwise they will break until v16 migration is complete)
This change will prevent new installations if an unwanted nx version is attempted to be used.
Notes for QA
> fix(root): add nx version ^15.7.2 as peerDep for each plugin

- packages/rest-client/src/generators/openapi-client/generator.spec.ts
- packages/rest-client/src/generators/openapi-client/generator.ts
- packages/rest-client/src/generators/openapi-client/schema.json
Issue 1: nx g openapi-client --help
Description of plugin is undefined
Issue 2: What is the relative path to you openapi schema?
Accepts no value, leading to the generator hanging
Issue 3: >  NX   'orval' is not recognized as an internal or external command
When running the generator the following message is displayed
Issue 4: Yaml path input
Specifying a directory will copy across that whole directory into the generated library and put this directory as the target in both orval and zod configs.
Need to verify that the input path is an actual file first of all
These are required to fulfil the completion of and acceptable solution for this generator.
Added extra checks in logic to account for such scenarios.
Link to documentation updated with …
> fix(rest-client): fix various misc bugs with openapi-client

- packages/common/core/package.json
set tslib dep to ^2.3.0 matching other plugins and use cases
Prevent unwanted warnings when npm i e.g. cypress plugin
Set to ^2.3.0 in package.json
Notes for QA
> fix(common-core): set tslib dep to ^2.3.0 matching other plugins and use cases

- packages/common/core/src/lib/findFile.spec.ts
- packages/common/core/src/lib/findFile.ts
- packages/common/core/src/lib/index.ts
- packages/common/core/src/lib/nonMonorepo.spec.ts
- packages/common/core/src/lib/nonMonorepo.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/next/src/generators/init/generator.ts
Add common util findFile and nonMonorepo to check for handling non monorepo env
Prevent users with non Nx monorepo env to install stacks plugins
Created common utils for the logic to check for such scenarios
Notes for QA
> fix(create): handle non monorepo environment

- .github/workflows/prerelease.yml
- e2e/azure-react-e2e/project.json
- packages/azure-react/project.json
Set workflow to releaseAs=premajor so we get v2-alpha versions.
Also comment out azure-react lint, test and version targets so they don't run as plugin is not used.
Notes for QA
> fix(root): temp change workflow to release as premajor for v2

- e2e/create-e2e/tests/create.spec.ts
- packages/create/bin/dependencies.ts
[6413](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/6413)
Ensure none is passed for e2eTestRunner if playwright or cypress selected.
As we have our own playwright and cypress implementations, we need to pass in as none.
Logic added to the create script args normalise method to ensure expected behaviour.
Notes for QA
> fix(create): add logic to normalise setting e2eTestRunner to none if playwright or cypress

- packages/common/core/src/utils/hasGeneratorExecuted.ts
[6423](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/6423)
Read package.json for workspace scope name for logging out in message.
npmScope attribute is no longer present inside nx.json
Read package.json name attribute and slice.
Notes for QA
> fix(common-core): read package json scope name for executed workspace

- packages/workspace/src/generators/init/generator.spec.ts
- packages/workspace/src/generators/init/utils/eslint.ts
add eslint config to enable a11y checks 
https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/6383
so that apps generated using stacks come with dev-time a11y out of the box
refer to screenshots in ADO
Notes for QA
> feat(workspace:init): add eslint a11y plugin to eslint config

- .github/workflows/release.yml
Added new enviornment variable, CI
The command `npx nx affected` expects to be run in an interactive session but in GHA there is no tty for this
Added `export CI=true` to the job
This has not been tested on a branch as it is restricted to running on the master branch
> Prevent NX from running in interactive mode

- e2e/workspace-e2e/tests/__snapshots__/workspace.spec.ts.snap
- packages/common/core/src/utils/hasGeneratorExecuted.ts
- packages/workspace/src/generators/init/utils/eslint.ts
Fix for 6471: Use existing getNpmScope function to get correct scope for eslint file.
npmScope attribute is no longer present inside nx.json
Export and use existing `getNpmScope` function from `hasGeneratorExecuted.ts`.
We could move this function into a standalone util file but would take extra work moving and updating tests.
Would be good to get this fix in and perhaps raise and improvement task to move to separate file if required.
Notes for QA
> fix(common-core): use getNpmScope function to get correct scope

- packages/rest-client/utils/versions.ts
Fix for 6434: Bump msw version to 1.2.3 which will in turn bump peer dep version of typescript and avoid conflict
rest-client generator fails on install
Bump msw version in `version.ts` to `1.2.3`
Notes for QA
> fix(workspace): bump msw version to avoid ts peer dep conflict

- packages/next/src/generators/init/__snapshots__/generator.spec.ts.snap
- packages/next/src/generators/init/generator.spec.ts
- packages/next/src/generators/init/generator.ts
- packages/next/src/generators/init/utils/react-axe.ts
- packages/next/src/utils/constants.ts
…fault
adds an a11y tool (react-axe) to all nextjs applications generated using stacks
for a11y enhancements
adding 2 function calls in next:init generator; one to add the react-axe devDependency and another to ensure the necessary config for react-axe initialisation is added to _app.tsx.
Notes for QA
> feat(next:init): add react-axe config to generated applications

- packages/rest-client/src/generators/bump-version/generator.spec.ts
- packages/rest-client/src/generators/bump-version/generator.ts
Incorrect message when folder does not match convention which leads to confusion
The issue is not the error itself but what is displays and that leads to confusion. We need a better message to explain why the command didn't work
Display a message that mentions that a folder does not follow convention and presents what the convention is.
No documentation needs to be changed. Added tests to check for changes
Notes for QA
Either run tests OR
follow steps in ticket: https://amido-dev.visualstudio.com/Amido-Stacks/_workitems/edit/6527
> [6527] Rest Client Error message - incorrect message when folder does not match convention

- CONTRIBUTING.md
- README.md
- packages/azure-node/README.md
- packages/create/README.md
- packages/cypress/README.md
- packages/logger/README.md
- packages/next/README.md
- packages/playwright/README.md
- packages/rest-client/README.md
- packages/workspace/README.md
Updates links in docs to point to the new documentation structure
> docs: update links in docs

- packages/rest-client/utils/versions.ts
Axios version embeeded in TypeScript file needed bumping
Bump Axios in TypeScript file.
Version pulled in dynamically.
N/A
```
√  nx run common-test:test  [local cache]
√  nx run workspace:test  [local cache]
√  nx run cypress:test  [local cache]
√  nx run next:test  [local cache]
√  nx run azure-react:test  [local cache]
√  nx run common-core:test  [local cache]
√  nx run playwright:test  [local cache]
√  nx run create:test  [local cache]
√  nx run azure-node:test  [local cache]
√  nx run logger:test  [local cache]
√  nx run rest-client:test (6s)
```
Notes for QA
> fix(rest-client): updated axios to 1.7.3

- package-lock.json
- package.json
- packages/rest-client/utils/versions.ts
- Axios 1.7.3 → 1.7.4 resolves CVE-2024-39338
- elliptic 6.5.6 → 6.5.7 resolves CVE-2024-42459, CVE-2024-42460 and CVE-2024-42461
Updated using `npm audit fix` bumps the versions of both Axios and Elliptic to non-vulnerable versions. Additionally updated Axios version in rest-client.
We are committed to resolving Critical, High and Medium vulnerabilities within a reasonable timeframe within Stacks to meet our obligations under ISO 27001, CyberEssentials Plus and numerous commitments to clients.
- `npm audit fix` bump axios and elliptic in `package.json`
- direct change of CONST in `AXIOS_VERSION`
```
√  nx run common-test:lint  [existing outputs match the cache, left as is]
√  nx run common-core:lint  [existing outputs match the cache, left as is]
√  nx run playwright:lint  [existing …
```
> fix(root): bump axios and elliptic versions

- .github/workflows/matrix-command.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
With migration from Volta to node we want to leverage `.nvmrc` to install the correct node version.
That means we need to checkout the code first before setting up node 😄
> ci(root): move node setup to after checkout

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
Commits raised in CI do not belong to any branches.
Not quite sure why, but believe it to be a combination of not specifying the ref in checkout and branch protection.
Explicitly calling the ref, I hope to see tags associated to commits that belong to a branch.
When we do a release we gather tags from commits. It will not observe commits that do not belong to any branches, resulting in the incorrect semver version produced which causes catastrophic failure when trying to push the same version up to npm.
> ci(root): attempt fix for commits not associated to branch

- package-lock.json
- package.json
Upgrades @storybook/nextjs to 8.5.6 to mitigate GHSA-vjh7-7g9h-fjfh in elliptic <= 6.6.0
Upgrades `@storybook/nextjs` to 8.5.6 to mitigate GHSA-vjh7-7g9h-fjfh in elliptic <= 6.6.0.
Critical (CVSS 9.0) vulnerability affecting a build-time dependency. We are committed to resolving Critical, High and Medium vulnerabilities within a reasonable timeframe within Stacks to meet our obligations under ISO 27001, CyberEssentials Plus and numerous commitments to clients.
```
npm install @storybook/nextjs@latest  
```
```
✔  nx run common-test:lint  [existing outputs match the cache, left as is]
✔  nx run common-core:lint  [existing outputs match the cache, left as is]
✔  nx run playwright:lint  [existing outputs match the cache, left as is]
✔  nx run cypress:lint  [existing outputs match the cache, …
```
> fix(stacks-nx-plugins): mitigate CVSS 9.0 vuln in crypto library
