Ensono/stacks-nx-plugins

- e2e/create-e2e/jest.config.ts
- e2e/create-e2e/project.json
- e2e/create-e2e/tests/create.spec.ts
- e2e/create-e2e/tsconfig.json
- e2e/create-e2e/tsconfig.spec.json
- package-lock.json
- package.json
- packages/common/core/project.json
- packages/common/e2e/src/executors/e2e/executor.ts
- packages/common/e2e/src/utils/registry.ts
- packages/create/.eslintrc.json
- packages/create/README.md
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
- packages/create/bin/exec.ts
- packages/create/bin/index.ts
- packages/create/bin/package-manager.ts
- packages/create/jest.config.ts
- packages/create/package.json
- packages/create/project.json
- packages/create/setup-test.ts
- packages/create/tsconfig.json
- packages/create/tsconfig.lib.json
- packages/create/tsconfig.spec.json
- packages/rest-client/project.json
- packages/workspace/project.json
Adds `@ensono-stacks/create-stacks-workspace`
```sh
npx @enosno-stacks/create-stacks-workspace [name] [options]
```
Custom options to be added as we develop. 
All unknown options are forwarded to `create-nx-workspace` under the hood.
> feat(create): create stacks workspace

- packages/playwright/src/generators/init/generator.ts
Add reminder message to set the required environment variables for applitools eyes.
> feat(playwright): add reminder for APPLITOOLS_API_KEY env variable

- e2e/azure-react-e2e/jest.config.ts
- e2e/azure-react-e2e/project.json
- e2e/azure-react-e2e/tests/azure-react.spec.ts
- e2e/azure-react-e2e/tsconfig.json
- e2e/azure-react-e2e/tsconfig.spec.json
- package-lock.json
- package.json
- packages/azure-react/.eslintrc.json
- packages/azure-react/README.md
- packages/azure-react/executors.json
- packages/azure-react/generators.json
- packages/azure-react/jest.config.ts
- packages/azure-react/package.json
- packages/azure-react/project.json
- packages/azure-react/src/generators/app-insights-web/files/src/app-insights-config.ts__template__
- packages/azure-react/src/generators/app-insights-web/files/src/index.ts__template__
- packages/azure-react/src/generators/app-insights-web/files/src/telemetry-provider.test.tsx__template__
- packages/azure-react/src/generators/app-insights-web/files/src/telemetry-provider.tsx__template__
- packages/azure-react/src/generators/app-insights-web/generator.spec.ts
- packages/azure-react/src/generators/app-insights-web/generator.ts
- packages/azure-react/src/generators/app-insights-web/schema.d.ts
- packages/azure-react/src/generators/app-insights-web/schema.json
- packages/azure-react/src/index.ts
- packages/azure-react/tsconfig.json
- packages/azure-react/tsconfig.lib.json
- packages/azure-react/tsconfig.spec.json
- packages/azure-react/utils/versions.ts
- tsconfig.base.json
Create azure-react plugin with app-insights-web generator.
> feat(azure-react): add azure-react plugin

- packages/playwright/src/generators/init/schema.json
https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5424
- add missing description for visualRegression flag
- add alias shorthand flag for options accessibility and visualRegression
> fix(playwright): add missing help docs description

- packages/common/core/src/lib/eslint.ts
replaced existing eslint merge with common util from common core
fix #5423
> fix(common-core): replaced existing eslint merge with common util

- packages/next/src/generators/init/generator.ts
> fix(next): handle undefined values in project config

- packages/azure-node/src/generators/app-insights/schema.json
prompt user for required prompts when running azure node init generator
fix #5417
> fix(azure-node): fix for schema options to prompt user

- e2e/playwright-e2e/tests/playwright.spec.ts
- packages/playwright/src/generators/init/files/accessibility/axe-accessibility.spec.ts__template__
- packages/playwright/src/generators/init/files/default/example.spec.ts__template__
- packages/playwright/src/generators/init/files/visualRegression/native/playwright-visual-regression.spec.ts__template__
- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/generator.ts
https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5434
- added optional flag to return updateDependencies util method
- fixed linting of template files
> fix(playwright): dependency issues

- packages/azure-node/README.md
- packages/azure-react/README.md
- packages/create/README.md
- packages/logger/README.md
- packages/next/README.md
- packages/playwright/README.md
- packages/rest-client/README.md
- packages/workspace/README.md
update readme of all nx plugins with template
fix #5392
> docs(root): update readme of all nx plugins with template

- packages/next/src/generators/next-auth/schema.json
> fix(next): --provider in next-auth generator should be an enum

- packages/next/src/generators/next-auth/__snapshots__/generator.spec.ts.snap
- packages/next/src/generators/next-auth/utils/redis-adapter.ts
Libs imports should start with `@` ;)
> fix(next): fix import path

- packages/azure-react/src/generators/app-insights-web/generator.spec.ts
- packages/azure-react/src/generators/app-insights-web/generator.ts
- packages/azure-react/src/generators/app-insights-web/schema.json
- packages/azure-react/tsconfig.lib.json
[5471](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5471)
- Converts connectionString to constantName format (uppercase and underscores)
- Updates tsconfig to resolve linting issues
- `-dir` flag updated to be `-d`
> fix(azure-react): resolve linting and connectionString format

- packages/next/src/generators/infrastructure/files/azure/build/helm/values-prod.yaml
- packages/next/src/generators/infrastructure/files/azure/build/helm/values.yaml
- packages/next/src/generators/infrastructure/files/common/Dockerfile
- packages/next/src/generators/infrastructure/utils/common.ts
- packages/next/src/generators/infrastructure/utils/terraform.ts
[5489](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5489)
- create method setPort for multiple uses
- pass port variable to helm values yaml
> fix(next): pass port variable to helm values yaml

- packages/common/core/src/lib/registry.ts
- packages/next/src/generators/infrastructure/files/azure/build/terraform/data.tf
- packages/next/src/generators/infrastructure/files/azure/build/terraform/main.tf
- packages/next/src/generators/infrastructure/files/azure/build/terraform/nonprod.tfvars
- packages/next/src/generators/infrastructure/files/azure/build/terraform/prod.tfvars
- packages/next/src/generators/infrastructure/files/azure/build/terraform/variables.tf
- packages/next/src/generators/infrastructure/utils/common.ts
- packages/next/src/generators/infrastructure/utils/terraform.ts
Some core infrastructure changes to improve generated deployment code.
> feat(next): add core infrastructure code changes

- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/utils/update-targets.ts
- packages/playwright/src/generators/init/utils/update-tasks-yamls.ts
Fix some file path and try to prevent duplication when generator run more than once
> fix(playwright): fix file paths

- packages/next/src/generators/infrastructure/files/azure/build/terraform/nonprod.tfvars
- packages/next/src/generators/infrastructure/files/azure/build/terraform/prod.tfvars
Fix formatting issue in generated terraform code.
> fix(next): fix terraform code in infrastructure generator

- packages/next/src/generators/next-auth/generator.spec.ts
- packages/next/src/generators/next-auth/generator.ts
- packages/next/src/generators/next-auth/utils/update-helm-templates.ts
- packages/next/src/generators/next-auth/utils/update-targets.ts
- packages/next/src/generators/next-auth/utils/update-terraform-files.ts
Add infra code for redis in next-auth generator, based on this PR https://github.com/amido/poc-nx-apps/pull/13/files
> feat(next): add redis infra code to generator

- packages/common/core/src/lib/registry.ts
- packages/next/src/generators/infrastructure/utils/common.ts
- packages/next/src/generators/infrastructure/utils/terraform.ts
- packages/workspace/src/generators/init/files/taskctl/common/build/taskctl/tasks.yaml
Various bug fixes for generated infra files
> Various bug fixes for generated infra files

- packages/create/bin/exec.ts
- packages/playwright/src/generators/init/generator.ts
- packages/playwright/src/generators/init/utils/exec.ts
- packages/playwright/src/generators/init/utils/init.ts
[5533](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5533)
> fix(playwright): potential fix for playwright init with console logs

- package-lock.json
- package.json
- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/generator.ts
[5540](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5540)
- set `@mands/nx-playwright` to `~0.2.3` in root package.json - minor here is used for breaking changes so best to keep it to auto update latest patch
- remove app.spec.ts in new generated e2e project
- update unit test
> fix(playwright): install latest @mands package and remove app.spec.ts on init

- packages/next/src/generators/infrastructure/generator.spec.ts
- packages/next/src/generators/infrastructure/utils/common.ts
- packages/next/src/generators/init/generator.spec.ts
Fix the custom server path in the generated Docker file.
> feat(next): fix custom server path in Dockerfile

- packages/next/src/generators/next-auth-redis/generator.ts
- packages/next/src/generators/next-auth-redis/utils/update-helm-templates.ts
- packages/next/src/generators/next-auth-redis/utils/update-targets.ts
- packages/next/src/generators/next-auth-redis/utils/update-terraform-files.ts
- packages/next/src/generators/next-auth/__snapshots__/generator.spec.ts.snap
- packages/next/src/generators/next-auth/utils/session-provider.ts
- fix typo in helm config template
- linting for auth session provider import order
- enable next-auth and redis config added into helm upgrade target
- prevent redis index file being removed
- helm template indentation
- update-terraform formatting
> fix(next): updates for next-auth and next-auth-redis generators

- packages/next/src/generators/next-auth/schema.d.ts
- packages/next/src/generators/next-auth/schema.json
- packages/next/src/generators/next-auth/utils/local-env.ts
Remove unused provider option from the code.
> fix(next): remove azureAdB2C from schema

- e2e/rest-client-e2e/tests/rest-client.spec.ts
- packages/common/core/src/lib/normalize-options.ts
- packages/rest-client/src/generators/bump-version/generator.spec.ts
- packages/rest-client/src/generators/bump-version/generator.ts
- packages/rest-client/src/generators/bump-version/schema.d.ts
- packages/rest-client/src/generators/bump-version/schema.json
Reverts amido/stacks-nx-plugins#126
> Revert "fix(rest-client): linting and generator config"

- e2e/rest-client-e2e/tests/rest-client.spec.ts
- packages/common/core/src/lib/normalize-options.ts
- packages/rest-client/src/generators/bump-version/generator.spec.ts
- packages/rest-client/src/generators/bump-version/generator.ts
- packages/rest-client/src/generators/bump-version/schema.d.ts
- packages/rest-client/src/generators/bump-version/schema.json
Reverts amido/stacks-nx-plugins#127
> Revert "Revert "fix(rest-client): linting and generator config""

- packages/common/e2e/src/utils/project.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.ts
- packages/create/bin/types.ts
Ticket: [TASK 5757](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5757)
- Add --useDev flag to create script to install `@dev` version of dependencies
> feat(create): add --useDev flag to create script

- packages/create/bin/dependencies.ts
Ticket [5757](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5757)
- Only append @dev to ensono-stacks packages
> fix(create): only get the dev version of the ensono-stacks plugins

- packages/logger/src/generators/winston/schema.json
- packages/next/src/generators/init-deployment/schema.json
- packages/next/src/generators/init/schema.json
- packages/next/src/generators/next-auth-redis-deployment/schema.json
- packages/playwright/src/generators/accessibility/schema.json
- packages/playwright/src/generators/init-deployment/schema.json
- packages/playwright/src/generators/init/schema.json
- packages/playwright/src/generators/visual-regression-deployment/schema.json
- packages/playwright/src/generators/visual-regression/schema.json
- packages/rest-client/src/generators/client-endpoint/schema.json
- packages/workspace/src/generators/init-deployment/schema.json
- packages/workspace/src/generators/init/schema.json
Ticket [5764](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5764)
- Add missing descriptions in generator schema
- Fix duplicated IDs in generator schema
> feat: add missing descriptions to schemas and fix schema ids

- packages/next/src/generators/next-auth/utils/constants.ts
Ticket: [5746](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5746)
- Update the next-auth package version
> chore(next): update next-auth to 4.20.1

- e2e/next-e2e/project.json
- e2e/playwright-e2e/project.json
- packages/common/core/src/index.ts
- packages/common/core/src/test/index.ts
- packages/common/core/src/test/testInitStacksConfig.ts
- packages/common/core/src/utils/hasGeneratorExecuted.ts
- packages/next/src/generators/init-deployment/generator.spec.ts
- packages/next/src/generators/init/generator.spec.ts
- packages/next/src/generators/next-auth-redis-deployment/generator.spec.ts
- packages/next/src/generators/next-auth-redis/generator.spec.ts
- packages/next/src/generators/next-auth/generator.spec.ts
- packages/playwright/src/generators/accessibility/generator.spec.ts
- packages/playwright/src/generators/accessibility/generator.ts
- packages/playwright/src/generators/init-deployment/generator.spec.ts
- packages/playwright/src/generators/init-deployment/generator.ts
- packages/playwright/src/generators/init/generator.spec.ts
- packages/playwright/src/generators/init/generator.ts
- packages/playwright/src/generators/visual-regression-deployment/generator.spec.ts
- packages/playwright/src/generators/visual-regression-deployment/generator.ts
- packages/playwright/src/generators/visual-regression/generator.spec.ts
- packages/playwright/src/generators/visual-regression/generator.ts
[5726](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5726)
- add logic to check if generators already executed
> feat(playwright): plugin enhancement

- e2e/azure-node-e2e/project.json
- packages/azure-node/src/generators/app-insights-deployment/generator.spec.ts
- packages/azure-node/src/generators/app-insights-deployment/generator.ts
- packages/azure-node/src/generators/app-insights/generator.spec.ts
- packages/azure-node/src/generators/app-insights/generator.ts
[5726](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5726)
- implement executedGenerators check
> feat(azure-node): plugin enhancement

- e2e/azure-react-e2e/project.json
- packages/azure-react/src/generators/app-insights-web/generator.spec.ts
- packages/azure-react/src/generators/app-insights-web/generator.ts
[5726](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5726)
- implement executedGenerators check
> feat(azure-react): plugin enhancement

- packages/next/src/generators/init-deployment/utils/common.ts
- Store version in environment file for `helm-upgrade` target
- Set version argument for `helm-upgrade` command
> fix(next): set version for Helm upgrade

- packages/azure-node/src/generators/app-insights/generator.ts
- packages/next/src/generators/init/generator.ts
- packages/next/src/generators/next-auth-redis/generator.ts
- packages/playwright/src/generators/init/generator.ts
- packages/playwright/src/generators/visual-regression/generator.ts
- packages/workspace/src/generators/init/generator.ts
Ticket: [5765](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5765)
- Add extra information to playwright deployment generator message
- Move deployment generator messages in callbacks so that's the last thing printed on the terminal
> fix: move the generator messages to the callback

- packages/common/test/README.md
- packages/common/test/project.json
> fix(common-test): fix typos

- packages/azure-node/src/generators/app-insights-deployment/generator.ts
- packages/azure-node/src/generators/app-insights-deployment/utils/update-dockerfile.ts
- Check if Dockerfile exists
- Replace `next start` command with `node server`
- Add copy for server files
> fix(azure-node): update dockerfile if it exists for custom server

- packages/workspace/src/generators/init/files/lintstaged/lint-staged.config.js
[5788](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5788)
- update lint-staged.config.js inside workspace generator
> fix(workspace): husky lint helm files with new updated structure

- packages/next/src/generators/init-deployment/utils/common.ts
[5956](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5956)
- add helm lib project to implicit deps
> fix(next): helm-upgrade versioning

- packages/next/src/generators/init-deployment/utils/common.ts
Ticket: [5948](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5948)
- Add no-cache to the container target in the project.json
> fix(next): add no-cache to container target

- packages/playwright/src/generators/init/generator.ts
- packages/playwright/src/generators/init/utils/update-playwright-config-base.ts
Ticket: [5960](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5960)
- Prevent duplicated variable declarations in playwright.base.config.ts
- Prevent duplicated object attributes in playwright.base.config.ts
> fix(playwright): prevent duplication in playwright.base.config

- packages/playwright/src/generators/init-deployment/generator.spec.ts
- packages/playwright/src/generators/init-deployment/utils/update-azdevops-build.ts
Ticket: [5953](https://dev.azure.com/amido-dev/Amido-Stacks/_workitems/edit/5953)
- Add condition to PublishTestResults steps
> feat(playwright): only publish test result if its available

- .github/pull_request_template.md
- .github/workflows/release.yml
Updates git config  for AmidoStacks user and adds PR template files
> Updates Git User & Adds PR Template

- .github/workflows/prerelease.yml
Updates prerelease config
Invalid existing config
Standard YML
Merge to Main and let build run.
> Updates prerelease config

- packages/azure-node/src/generators/app-insights-deployment/generator.ts
- packages/common/test/src/lib/stacks-attributes.ts
- packages/next/src/generators/init-deployment/generator.ts
- packages/next/src/generators/init-deployment/utils/add-infrastructure.ts
- packages/playwright/src/generators/init-deployment/generator.ts
Fix some outstanding text changes for correct executedDepdndantGenerator func and add infra warning message
To correct usage of code and feedback
Update text copy to correct expectation
Notes for QA
> fix(root): misc fixes

- packages/create/bin/create-stacks-workspace.ts
> fix(create): lock nrwl package versions to nx version

- packages/cypress/src/generators/init/files/e2e-folder/cypress/support/e2e.ts__template__
- packages/cypress/src/generators/init/files/root/cypress.config.base.ts__template__
- packages/cypress/src/generators/init/generator.spec.ts
- packages/cypress/src/generators/init/generator.ts
- packages/cypress/src/versions.ts
Add in the cypress grep plugin to cypress:init
To allow users to run specific tests with the nx cypress executor
> Add in cypress grep reqs

- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
- packages/create/bin/types.ts
Add Cypress to the create script
To allow users to provision a new workspace/app with the cypress e2e test runner
> Add cypress to create script

- e2e/cypress-e2e/tests/cypress.spec.ts
- packages/cypress/package.json
- packages/cypress/src/generators/accessibility/generator.spec.ts
- packages/cypress/src/generators/accessibility/generator.ts
- packages/cypress/src/generators/init/files/e2e-folder/cypress/tsconfig.json__template__
- packages/cypress/src/generators/init/generator.spec.ts
- packages/cypress/src/generators/init/generator.ts
- packages/cypress/src/generators/init/utils/update-files.ts
Fix the issue where you cannot compile the next application when cypress is added
To allow the cypress and application directories to be compiled seperated, whereby cypress is compiled without isolatedModules set
Amend the tsconfig and eslint files within the application for cypress
> Fix for cypress isolated modules

- packages/common/e2e/src/utils/package-manager.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.spec.ts
- packages/create/bin/dependencies.ts
- packages/create/bin/types.ts
Add cypress to create script
So Cypress files can be installed on creation of new workspace
Add cypress to E2ETestRunner enum
Add types and unit tests
Refactor logic for test runner selection
Notes for QA
> fix(create): add cypress related changes to create script

- packages/cypress/src/generators/accessibility/utils/update-files.ts
Fix import order of the axe-result import for linting
> Fix import order

- packages/workspace/src/generators/init-deployment/generator.ts
Add .nx-conainer to gitignore
It is not something we need to push into the git repo.
Add it to gitignore.
Notes for QA
> fix(workspace): add nx-container to gitignore

- packages/cypress/src/generators/init/files/e2e-folder/cypress/support/e2e.ts__template__
Amend the e2e.ts file to use relative paths to screenshots within html reports
To properly display screenshots within html reports
Amend the e2e.ts__template file with new relative path
> Update e2e.ts template for relative screenshot paths

- package-lock.json
- package.json
Upgrade version to fix dependabot alert.
Because of HIGH vulnerability.
Upgarde YAML package version.
Notes for QA
> chore(root): update yaml package

- e2e/next-e2e/tests/next.spec.ts
- packages/next/generators.json
- packages/next/src/generators/next-auth-redis-deployment/generator.ts
- packages/next/src/generators/next-auth-redis/generator.ts
Remove next-auth-redis and respective deployment generators
next-auth-redis has never been verified as working.
Remove references to next-auth-redis and next-auth-redis-deployment from generators.json.
Notes for QA
> fix(next): remove next-auth-redis as it's not working

- packages/playwright/project.json
Reverts amido/stacks-nx-plugins#217
> Revert "refactor(playwright): set prerelease push config to false"

- packages/playwright/README.md
release v1
BREAKING CHANGE: release v1
Notes for QA
> refactor(playwright): add space

- packages/cypress/package.json
release v1
BREAKING CHANGE: release v1
Notes for QA
> feat(cypress): update version to v1

- packages/azure-node/README.md
- packages/common/core/README.md
- packages/common/e2e/README.md
- packages/common/test/README.md
- packages/create/README.md
- packages/cypress/README.md
- packages/logger/README.md
- packages/rest-client/README.md
- packages/workspace/README.md
> Release plugins v1

- .github/workflows/prerelease.yml
remove releaseAs flag in workflow so version can run as expected
Notes for QA
> fix(root): remove releaseAs flag in workflow so version can run as expected

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> feat(root): manual change version target to upgrade major version

- .github/workflows/release.yml
- packages/azure-node/README.md
- packages/common/core/README.md
- packages/common/e2e/README.md
- packages/common/test/README.md
- packages/create/README.md
- packages/cypress/README.md
- packages/logger/README.md
- packages/next/README.md
- packages/playwright/README.md
- packages/rest-client/README.md
- packages/workspace/README.md
> Release v2

- .github/workflows/release.yml
> fix(root): release v2: add releaseAs=major to release workflow

- .github/workflows/prerelease.yml
- .github/workflows/release.yml
> feat(root): remove releaseAs=major from release workflows

- e2e/cypress-e2e/tests/cypress.spec.ts
- packages/common/e2e/src/executors/e2e/executor.ts
- packages/common/e2e/src/utils/run-target-utils.ts
- packages/cypress/src/generators/init/__snapshots__/generator.spec.ts.snap
- packages/cypress/src/generators/init/generator.spec.ts
Improve e2e and unit test coverage for cypress plugin
To improve ability to catch issues early
> test(cypress): improved e2e and unit test coverage

- CONTRIBUTING.md
- e2e/azure-node-e2e/project.json
- e2e/azure-node-e2e/tests/azure-node.spec.ts
- e2e/cypress-e2e/tests/cypress.spec.ts
- e2e/logger-e2e/tests/logger.spec.ts
- e2e/next-e2e/tests/next.spec.ts
- e2e/playwright-e2e/tests/playwright.spec.ts
- e2e/rest-client-e2e/tests/rest-client.spec.ts
- packages/azure-node/src/generators/app-insights/__snapshots__/generator.spec.ts.snap
- packages/azure-node/src/generators/app-insights/generator.spec.ts
- packages/common/e2e/src/utils/package-manager.ts
- packages/common/e2e/src/utils/project.ts
Adding additional unit and e2e tests for azure-node plugin. Also includes some small refactor around installing packages.
To provide further test coverage
Notes for QA
> chore: refactor and additions to azure node tests

- .husky/prepare-commit-msg
Potential fix for the pre-release pipeline
Notes for QA
> fix: husky prepare commit msg

- e2e/rest-client-e2e/tests/rest-client.spec.ts
- packages/rest-client/src/generators/client-endpoint/__snapshots__/generator.spec.ts.snap
- packages/rest-client/src/generators/client-endpoint/generator.spec.ts
- packages/rest-client/src/generators/http-client/__snapshots__/generator.spec.ts.snap
- packages/rest-client/src/generators/http-client/generator.spec.ts
- packages/rest-client/src/generators/openapi-client/__snapshots__/generator.spec.ts.snap
- packages/rest-client/src/generators/openapi-client/generator.spec.ts
Add more unit and e2e tests for rest-client plugin. Also includes some refactors.
To add additional test coverage
Notes for QA
> chore: add more tests for rest-client

- e2e/create-e2e/tests/create.spec.ts
- packages/create/bin/create-stacks-workspace.spec.ts
- packages/create/bin/create-stacks-workspace.ts
- packages/create/bin/dependencies.spec.ts
Fixes to how arguments are verified when create a stacks workspace. Also added unit tests to verify this functionality.
Notes for QA
> fix: fixes for create stacks workspace

- docs/common_problems.adoc
- docs/know_issues.adoc
Creating a docs folder and two documents, known issues and common problems.
We want to have a docs folder that contains all documentation going forwards. This will eventually be used to publish documentation to a website.
Notes for QA
> chore: add docs for known issues and common problems

- .github/workflows/nxlatest-e2e.yml
- e2e/create-e2e/tests/create.spec.ts
- packages/common/e2e/src/utils/package-manager.ts
- packages/common/e2e/src/utils/project.ts
- packages/common/e2e/src/utils/versions.ts
Ability to run the tests with the latest version of Nx on a weekly schedule.
Running tests against latest version of Nx will allow us to catch issues in advance, and determine if we want to bump the versions we have set.
Notes for QA
> chore: run tests with latest nx

- packages/workspace/src/generators/init/generator.spec.ts
- packages/workspace/src/generators/init/generator.ts
- packages/workspace/src/generators/init/schema.d.ts
- packages/workspace/src/generators/init/utils/constants.ts
- packages/workspace/src/generators/init/utils/nvm.ts
> feat(create): added nvm into init generator

- packages/workspace/src/generators/init/schema.json
Add nvm to schema.json to fix issue where nvm file is not created
Notes for QA
> fix(): add nvm to schema

- e2e/workspace-e2e/tests/__snapshots__/workspace.spec.ts.snap
- packages/workspace/src/generators/init/generator.spec.ts
- packages/workspace/src/generators/init/utils/constants.ts
- packages/workspace/src/generators/init/utils/eslint.ts
Add the following eslint plugins and config.
eslint-plugin-jest
eslint-plugin-jest-dom
eslint-plugin-no-unsanitized
Bring stacks inline with plugins successfully used on previous projects.
Update generator to add plugin packages and config
Notes for QA
> feat(workspace): add eslint plugins

- .github/workflows/release.yml
Temporary change to force a new release
Previous release failed due to NPM publish issue. We want to force a new release even though nothing has changed.
Notes for QA
> chore: temp fix to force new release

- .github/workflows/release.yml
Remove flag to allow empty release
This was a temporary change after NPM failed to publish, to force a new release. Reverting back now the release has been processed.
Notes for QA
> chore: remove flag to allow empty release

- packages/playwright/src/generators/accessibility/generator.spec.ts
- packages/playwright/src/generators/init/__snapshots__/generator.spec.ts.snap
- packages/playwright/src/generators/init/files/example.spec.ts__template__
- packages/playwright/src/generators/init/generator.ts
- packages/playwright/src/generators/visual-regression/generator.spec.ts
Playwright generator example spec has typescript errors
Add type and update tsconfig
Notes for QA
> fix: add type and update tsconfig

- package-lock.json
- packages/azure-node/package.json
- packages/azure-react/package.json
- packages/cypress/package.json
- packages/logger/package.json
- packages/next/package.json
- packages/playwright/package.json
- packages/playwright/src/generators/visual-regression-deployment/files/native-build/azuredevops-updatesnapshots.yaml
- packages/rest-client/package.json
- packages/workspace/package.json
- packages/workspace/src/generators/init-deployment/files/taskctl/azdo/build/azDevOps/azuredevops-stages.yaml
> chore(root): updated package.json and yml files to use ensono github

- packages/create/bin/create-stacks-workspace.ts
Removing test runner descriptions from create workspace script as they are unnecessary.
Notes for QA
> fix: remove test runner descriptions

- packages/playwright/src/generators/init/generator.ts
6960: Install playwright browsers with generator
When example tests run, if the user doesn't have the playwright browsers installed all the tests will fail.
execute `npx install playwright` in the playwright init generator
Notes for QA
> feat: add command to install playwright

- packages/create/bin/dependencies.ts
6965 - Remove unnecessary log message when running the nx generator.
Message is confusing
Notes for QA
> fix: remove unnecessary log message

- packages/create/bin/create-stacks-workspace.ts
> fix(root): skipped e2e test for workspace

- packages/next/src/generators/storybook/utils/constants.ts
- packages/next/src/generators/storybook/utils/dependancies.ts
> fix(next): added webpack as a dev dep

- e2e/cypress-e2e/tests/cypress.spec.ts
- e2e/next-e2e/tests/next.spec.ts
- packages/common/e2e/src/utils/run-target-utils.ts
- packages/next/src/generators/storybook/generator.spec.ts
Add tests for Storybook custom component command
Notes for QA
> feat: add tests for custom component command

- packages/create/package.json
- packages/workspace/package.json
> fix(root): use dev tag for @ensono-stacks/core

- e2e/next-e2e/tests/next.spec.ts
- packages/next/src/generators/init-deployment/__snapshots__/generator.spec.ts.snap
- packages/next/src/generators/init-deployment/utils/common.ts
fix the e2e tests for next init deployment
it's excluded from the pipelines. Reenabling it after nx and next upgrade
remove the targets.serve code
Notes for QA
> fix(next): remove the target serve as it does not exist in latest nextjs

- jest.config.ts
- package-lock.json
- package.json
- packages/create/bin/create-stacks-workspace.ts
Create script fails to remove folder in --overwrite on windows when some files/folders are engaged with the os.
> fix(create): stacks-cli remove folder behaviour for windows

- packages/create/package.json
> fix(create): add dependency to package

- packages/create/bin/create-stacks-workspace.ts
- packages/create/package.json
> fix(create): attempt to clone project from tmp if cwd matches target

- .husky/prepare-commit-msg
> fix(root): rewrite compliant sh script

- nx.json
- packages/create/package.json
> fix(root): build dependencies before versioning

- packages/create/bin/create-stacks-workspace.ts
> fix(create): exclude nx cache folder from copy

- package-lock.json
- package.json
Security updates covering [Dependabot](https://github.com/Ensono/stacks-nx-plugins/security) and `npm audit fix`:
- Server-Side Request Forgery in axios (CVE-2024-39338)
- Express.js Open Redirect in malformed URLs (CVE-2024-29041)
We are committed to resolving Critical, High and Medium vulnerabilities within a reasonable timeframe within Stacks to meet our obligations under ISO 27001, CyberEssentials Plus and numerous commitments to clients.
Changes were made in reference to the [Dependabot](https://github.com/Ensono/stacks-nx-plugins/security) tab and the use of `npm audit fix`. Each commit was independently tested locally using `npm run test`.
```shell
> stacks-nx-plugins@0.0.0 test
> nx run-many --target test --all --parallel 8
√  nx run common-test:test (16s)
√  nx run create:test …
```
> Security Updates 2024-08-13

- .github/workflows/agents.yml
- .github/workflows/main.yml
- .github/workflows/matrix-e2e.yml
- .github/workflows/nxlatest-e2e.yml
- .github/workflows/prerelease.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- nx.json
feat(nx-cloud): setup nx cloud workspace 
This commit sets up Nx Cloud for your Nx workspace, enabling distributed caching and the Nx Cloud GitHub integration for fast CI and improved developer experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/66eacb38c92a39ba31162cc9/workspaces/671f85a6e3eeb14c0175569d
**Note:** This commit attempts to maintain formatting of the nx.json file, however you may need to correct formatting by running an nx format command and committing the changes.
> feat(nx-cloud): setup nx workspace

- nx.json
- packages/azure-node/package.json
- packages/azure-react/package.json
- packages/create/package.json
- packages/cypress/README.md
- packages/cypress/package.json
- packages/logger/package.json
- packages/next/package.json
- packages/playwright/package.json
- packages/rest-client/package.json
- packages/workspace/package.json
> fix(cypress): add deprecation notice
